version: 2
project_name: procks
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    goarm:
    - 7
    ignore:
    - goos: linux
      goarch: arm64
    main: ./cmd/client
archives:
  - formats:
    - binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    # Per https://goreleaser.com/customization/archive/#packaging-only-the-binaries
    files:
      - none*
changelog:
  filters:
    exclude:
      - '^Merge pull request #'